name: Deploy static content to Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
      - name: Setup zig
        uses: mlugg/setup-zig@v1.2.0
        with:
          version: 0.13.0
      - name: Build static site
        run: zig build --summary new
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: zig-out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
